# Variable 'python.version' was defined in the Variables tab
# Multi-job configuration must be converted to matrix strategy: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration
trigger:
  branches:
    include:
    - master
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Phase_1
  displayName: Build and Test
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python $(python.version)
    inputs:
      versionSpec: $(python.version)
      addToPath: false
  - task: CmdLine@2
    displayName: Install dependencies
    inputs:
      script: python -m pip install --upgrade pip && pip install -r requirements.txt
  - task: CmdLine@2
    displayName: pytest
    inputs:
      script: >-
        pip install pytest-django

        pip install pytest && pytest app/test.py --doctest-modules --junitxml=junit/test-results.xml
  - task: PublishTestResults@2
    displayName: Publish Test Results **/test-results.xml
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: Python $(python.version)
- job: Phase_2
  displayName: Publish
  dependsOn: Phase_1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python >= 3.6
    inputs:
      versionSpec: '>= 3.6'
      addToPath: false
  - task: CmdLine@2
    displayName: Build sdist
    inputs:
      script: python setup.py sdist
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dist'
    inputs:
      PathtoPublish: dist
      ArtifactName: dist
...
